import { chromium } from "playwright";
const base = "http://127.0.0.1:4320";
const token = await fetch(new URL("/api/invite", base), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: "friends-2026" }) }).then(async (r) => ((await r.json()) as { token: string }).token);
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on("console", (m) => { if (m.type() === "error") console.log("[console]", m.text().slice(0, 160)); });
await page.goto(base);
await page.evaluate((t) => localStorage.setItem("sparkbox:key:sparkbox", t), token);
await page.getByLabel("New project name").fill("Diag2");
await page.getByRole("button", { name: "Create" }).click();
await page.getByText("Sandbox ready").waitFor({ state: "attached", timeout: 240_000 });
type Exec = (c: string) => Promise<{ stdout: string; stderr: string; exitCode: number }>;
type Write = (p: string, c: string) => Promise<void>;
const run = (c: string) => page.evaluate((c) => (window as unknown as { sparkboxExec: Exec }).sparkboxExec(c), c);
const write = (p: string, c: string) => page.evaluate((a: { p: string; c: string }) => (window as unknown as { sparkboxWrite: Write }).sparkboxWrite(a.p, a.c), { p, c });
const show = (label: string, r: { stdout: string; stderr: string; exitCode: number }) => console.log(`== ${label} (exit ${r.exitCode})\n${(r.stdout + r.stderr).trim().slice(0, 1600)}`);
await write("package.json", JSON.stringify({ name: "diag", private: true, type: "module", pnpm: { overrides: { rolldown: "1.2.3" } } }, null, 2));
await write(".npmrc", "node-linker=isolated\n");
await write("load.mjs", "try { const r = await import('rolldown'); console.log('rolldown loaded', Object.keys(r).slice(0,5).join(',')); } catch (e) { console.log('LOAD FAIL', e && e.stack ? e.stack.split('\\n').slice(0, 14).join('\\n') : e); }\n");
await write("index.html", '<!doctype html><html><body><h1 id="t">hello vite</h1><script type="module" src="/main.js"></script></body></html>');
await write("main.js", "console.log('hi')\n");
await write("vite.config.js", "export default { server: { watch: { usePolling: true } }, build: { cssMinify: false } };\n");
await write("run.sh", "cd /workspace\nnode node_modules/vite/bin/vite.js --host 0.0.0.0 --port 5173 > vite.log 2>&1 &\nsleep 25\necho '--- vite.log ---'\ncat vite.log\necho '--- GET ---'\nnode -e \"fetch('http://127.0.0.1:5173/').then(r=>r.text()).then(t=>console.log('GET ok', t.includes('hello vite'), t.length)).catch(e=>console.log('ERR', e.message))\"\n");
show("env", await run("node -e \"console.log(process.platform, process.arch, process.version); try{require('worker_threads');console.log('worker_threads ok')}catch(e){console.log('worker_threads missing', e.message)}; try{require('wasi');console.log('wasi ok')}catch(e){console.log('wasi missing', e.message)}\""));
show("install", await run("pnpm add -D vite@8.2.0 @rolldown/binding-wasm32-wasi@1.2.3 --ignore-scripts > install.log 2>&1; echo exit=$?; tail -2 install.log; node -p \"require('rolldown/package.json').version\""));
show("load rolldown", await run("node load.mjs 2>&1"));
show("vite version", await run("node node_modules/vite/bin/vite.js --version 2>&1"));
show("dev", await run("bash run.sh 2>&1"));
await browser.close();
