import { chromium } from "playwright";
const base = "http://127.0.0.1:4320";
const token = await fetch(new URL("/api/invite", base), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ code: "friends-2026" }) }).then(async (r) => ((await r.json()) as { token: string }).token);
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
page.on("console", (m) => { if (m.type() === "error") console.log("[console]", m.text().slice(0, 160)); });
await page.goto(base);
await page.evaluate((t) => localStorage.setItem("sparkbox:key:sparkbox", t), token);
await page.getByLabel("New project name").fill("Vite7");
await page.getByRole("button", { name: "Create" }).click();
await page.getByText("Sandbox ready").waitFor({ state: "attached", timeout: 240_000 });
type Exec = (c: string) => Promise<{ stdout: string; stderr: string; exitCode: number }>;
type Write = (p: string, c: string) => Promise<void>;
const run = (c: string) => page.evaluate((c) => (window as unknown as { sparkboxExec: Exec }).sparkboxExec(c), c);
const write = (p: string, c: string) => page.evaluate((a: { p: string; c: string }) => (window as unknown as { sparkboxWrite: Write }).sparkboxWrite(a.p, a.c), { p, c });
const timed = async (label: string, command: string, ms = 120_000) => {
  const t = Date.now();
  const r = await Promise.race([run(command), new Promise<null>((resolve) => setTimeout(() => resolve(null), ms))]);
  console.log(`== ${label} (${Math.round((Date.now() - t) / 1000)}s)`, r ? `exit ${r.exitCode}\n${(r.stdout + r.stderr).trim().slice(0, 1800)}` : "TIMEOUT");
  return r;
};
await write("package.json", JSON.stringify({ name: "v7", private: true, type: "module", scripts: { dev: "vite --host 0.0.0.0 --port 5173" }, pnpm: { overrides: { esbuild: "npm:esbuild-wasm@0.25.12" } } }, null, 2));
await write("index.html", '<!doctype html><html><head><meta charset="utf-8"><title>v7</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>');
await write("src/main.tsx", 'import { createRoot } from "react-dom/client";\nimport "./style.css";\nfunction App() { return <h1 id="t">hello vite react</h1>; }\ncreateRoot(document.getElementById("root")!).render(<App />);\n(window as any).__marker = ((window as any).__marker || 0) + 1;\n');
await write("src/style.css", "h1 { color: rgb(10, 20, 30); }\n");
await write("vite.config.js", 'import react from "@vitejs/plugin-react";\nexport default { plugins: [react()], server: { watch: { usePolling: true } } };\n');
await write("run.sh", "cd /workspace\n(node node_modules/vite/bin/vite.js --host 0.0.0.0 --port 5173 > vite.log 2>&1 &)\nfor i in 1 2 3 4 5 6 7 8 9 10 11 12; do sleep 5; if grep -q 'Local:' vite.log; then break; fi; done\necho '--- vite.log ---'\ncat vite.log | head -30\necho '--- GET ---'\nnode -e \"fetch('http://127.0.0.1:5173/').then(r=>r.text()).then(t=>console.log('GET ok', t.includes('main.tsx'), t.length)).catch(e=>console.log('ERR', e.message))\"\nnode -e \"fetch('http://127.0.0.1:5173/src/main.tsx').then(r=>r.text()).then(t=>console.log('TSX transformed', t.includes('jsxDEV')||t.includes('createElement')||t.includes('jsx('), t.slice(0,160).replace(/\\n/g,' ')))\"\n");
await timed("install", "pnpm add -D vite@7 @vitejs/plugin-react@5 --ignore-scripts > install.log 2>&1; pnpm add react react-dom --ignore-scripts >> install.log 2>&1; echo exit=$?; tail -2 install.log; node -p \"require('esbuild/package.json').name + ' ' + require('esbuild/package.json').version\"", 300_000);
await timed("esbuild wasm", "node -e \"const e=require('esbuild');e.transform('const a: number = 1',{loader:'ts'}).then(r=>console.log('esbuild ok:', r.code.trim())).catch(e=>console.log('esbuild ERR', e.message))\"", 120_000);
await timed("dev", "bash run.sh 2>&1", 180_000);
await browser.close();
